services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    sysctls:
      net.core.somaxconn: "65535"
    command:
      - valkey-server
      - --save
      - ""
      - --appendonly
      - "no"
      - --io-threads
      - "4"
      - --io-threads-do-reads
      - "yes"
      - --tcp-backlog
      - "65535"
      - --lazyfree-lazy-user-del
      - "yes"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_NODENAME: rabbit@rabbitmq
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -os_mon start_disksup false
    ports:
      - "5672:5672"
      - "15672:15672"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq-advanced.config:/etc/rabbitmq/advanced.config:ro
volumes:
  rabbitmq-data:
